# -*- coding: utf-8 -*-
"""module-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMejJOQWu28_rSQSlmdGGS6RjHwqBgc6
"""

import pandas as pd

# Load dataset
df = pd.read_csv("data.csv")

# Check first few rows
print(df.head())

# Check dataset info
df.info()

# Check for null values
print(df.isnull().sum())

# Get basic statistics
print(df.describe())

# Drop rows with missing MSRP (target column)
df = df.dropna(subset=['MSRP'])

# Fill missing values for other columns
df['Engine HP'].fillna(df['Engine HP'].median())
df['Engine Cylinders'].fillna(df['Engine Cylinders'].median())
df['Transmission Type'].fillna('Unknown')

# remove duplicates
df.drop_duplicates(inplace=True)

# removing outliers
# Example: Remove cars with MSRP > 500,000 as outliers
df = df[df['MSRP'] < 500000]

import matplotlib.pyplot as plt
import seaborn as sns

# Distribution of MSRP
plt.figure(figsize=(8,5))
sns.histplot(df['MSRP'], bins=50, kde=True)
plt.title('Distribution of MSRP')
plt.show()

# Relationship between Engine HP and MSRP
plt.figure(figsize=(8,5))
sns.scatterplot(x='Engine HP', y='MSRP', data=df)
plt.title('Engine HP vs MSRP')
plt.show()

